//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowroomManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class group_objects
    {
        public int group_id { get; set; }
        public int object_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual group group { get; set; }
        public virtual objects @object { get; set; }
    }
}
