//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowroomManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class showroomEntities : DbContext
    {
        public showroomEntities()
            : base("name=showroomEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<group> groups { get; set; }
        public virtual DbSet<@object> objects { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<organization> organizations { get; set; }
        public virtual DbSet<pre_order> pre_order { get; set; }
        public virtual DbSet<purchase_order> purchase_order { get; set; }
        public virtual DbSet<service_order> service_order { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<vehicle> vehicles { get; set; }
        public virtual DbSet<vehicle_data> vehicle_data { get; set; }
        public virtual DbSet<vehicle_image> vehicle_image { get; set; }
        public virtual DbSet<vehicle_order> vehicle_order { get; set; }
        public virtual DbSet<vehicle_purchase> vehicle_purchase { get; set; }
        public virtual DbSet<vehicle_service> vehicle_service { get; set; }
    }
}
