//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowroomManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pre_order
    {
        public int vehicle_id { get; set; }
        public int customer_id { get; set; }
        public string status { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual vehicle_data vehicle_data { get; set; }
    }
}
