//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowroomManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase_order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public purchase_order()
        {
            this.vehicle_purchase = new HashSet<vehicle_purchase>();
        }
    
        public int purchase_id { get; set; }
        public Nullable<System.DateTime> date_purchase { get; set; }
        public Nullable<int> manage_by { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vehicle_purchase> vehicle_purchase { get; set; }
        public virtual user user { get; set; }
    }
}
