//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowroomManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicle_image
    {
        public int image_id { get; set; }
        public Nullable<int> vehicle_id { get; set; }
        public string image_url { get; set; }
    
        public virtual vehicle_data vehicle_data { get; set; }
    }
}
