//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowroomManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicle_purchase
    {
        public int vehicle_id { get; set; }
        public int purchase_order_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> price { get; set; }
    
        public virtual purchase_order purchase_order { get; set; }
        public virtual vehicle_data vehicle_data { get; set; }
    }
}
